# You can use a Docker image from Docker Hub or your own container
# registry for your build environment.
image: golang:latest

pipelines:
  default:
    - step:
        script:
          - mkdir $GOPATH/pkg
          - mkdir -p $GOPATH/src/bitbucket.org
          - cp -vr ../build $GOPATH/src/bitbucket.org/.
          - cd $GOPATH/src/bitbucket.org/build
          - go get ./...
          - go test
