version: "2"
services:
  web:
      container_name: web
      image: web
      build: web/.
      env_file:
       - database.env
       - app.env
      restart: on-failure
      depends_on:
        - migrate
      links:
        - mysql
      ports:
        - 8082:8082
      volumes:
         - ./web:/go/src/bitbucket.org/matchmove/accessman/web
         - ./configs/web.json:/go/src/bitbucket.org/matchmove/accessman/web/configs/web.json

